name: do_an_tot_nghiep
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  cloud_firestore: ^5.6.5
#  firebase_core: ^3.12.1
  flutter_image_slideshow: ^0.1.6
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
#  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
#  url_launcher: ^6.3.1
##  native_ar_viewer: ^0.0.2
#  permission_handler: ^11.4.0
#  flutter_inappwebview: ^6.1.5
  get: ^4.7.2
#  flutter_3d_controller: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/animation/
    - assets/glb/
    - assets/
  fonts:
    - family: ARSans
      fonts:
        - asset: assets/font/SVNGilroy-Regular.otf